import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { axeAccessibilityReporter } from "@/utils/axeAccessibilityReporter";

const inter = Inter({ subsets: ["latin"] });

axeAccessibilityReporter();

export const metadata: Metadata = {
  title: "Desenvolvendo Post Page Acessível",
  description: "Generated by create next app",
};

export default function RootLayout({

  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
